# ---------------------------------------------------------------------
#  Mosquitto - configuracion para el Modulo 1 (sin TLS)
#  La seguridad se agrega en el Modulo 3, Practica 11.
# ---------------------------------------------------------------------
listener 1883
allow_anonymous true

# WebSocket: permite conectar clientes desde el navegador
listener 9001
protocol websockets
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type all
connection_messages true
